#-------------------------------
# General Site Settings

title: Becoming a Brown
email: devtipsfordesigners@gmail.com

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Dan Brown and Tracey Sbrocca '
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section


google-analytics-ua: UA-100039439-1

