#-------------------------------
# General Site Settings

title: Becoming a Brown
email: mastasav@gmail.com

#-------------------------------
# SEO Section


seo:
  description: 'Holy Matrimony, Batman! Dan Brown and Tracey Sbrocca are getting married on November 11th! Join Dan and Tracey in celebrating their marriage and future.'


#-------------------------------
# Google Analytics Section


google-analytics-ua: UA-100039439-1

